import { describe, expect, it } from 'vitest'
import { bech32Encode, npubEncode } from './bech32.js'
import { hexToBytes } from './hex.js'

// ===========================================================================
// FROZEN GOLDEN VECTORS -- both taken VERBATIM from NIP-19's own published
// "Examples" section (raw.githubusercontent.com/nostr-protocol/nips/master/
// 19.md, fetched 2026-09-03), not generated by this implementation or any
// implementation in this repo. Independently re-verified with a hand-
// transcribed BIP-173 reference bech32 encoder written in Python (not
// TypeScript, not committed to this repo, scratch-only) before this file was
// written -- both matched byte-for-byte. If a change here makes a vector
// below fail, THE CHANGE IS WRONG, the same discipline as nip01.ts's and
// bundle-hash.ts's frozen tables.
// ===========================================================================

describe('npubEncode -- frozen golden vectors (NIP-19)', () => {
  it('vector 1', () => {
    const pubkey = hexToBytes('7e7e9c42a91bfef19fa929e5fda1b72e0ebc1a4c1141673e2794234d86addf4e')
    expect(npubEncode(pubkey)).toBe('npub10elfcs4fr0l0r8af98jlmgdh9c8tcxjvz9qkw038js35mp4dma8qzvjptg')
  })

  it('vector 2', () => {
    const pubkey = hexToBytes('3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d')
    expect(npubEncode(pubkey)).toBe('npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6')
  })

  it('rejects a pubkey that is not exactly 32 bytes', () => {
    expect(() => npubEncode(hexToBytes('aabb'))).toThrow(/32/)
    expect(() => npubEncode(new Uint8Array(33))).toThrow(/32/)
  })
})

describe('bech32Encode -- general shape', () => {
  it('always starts with hrp + "1"', () => {
    const encoded = bech32Encode('npub', [0, 1, 2, 3, 4])
    expect(encoded.startsWith('npub1')).toBe(true)
  })

  it('uses only the bech32 charset after the separator', () => {
    const encoded = bech32Encode('npub', [0, 1, 2, 3, 4])
    const [, data] = encoded.split('1')
    expect(data).toMatch(/^[qpzry9x8gf2tvdw0s3jn54khce6mua7l]+$/)
  })

  it('rejects a 5-bit word outside 0-31', () => {
    expect(() => bech32Encode('npub', [32])).toThrow()
    expect(() => bech32Encode('npub', [-1])).toThrow()
  })
})
